export const data = [
  {
    id: 1,
    date: "April 16th 2020",
    title: "The Mountains",
    credit: "John Appleseed",
    desktop: "/assets/stories/desktop/mountains.jpg",
    mobile: "/assets/stories/mobile/mountains.jpg",
  },
  {
    id: 2,
    date: "April 16th 2020",
    title: "Sunset Cityscapes",
    credit: "Benjamin Cruz",
    desktop: "/assets/stories/desktop/cityscapes.jpg",
    mobile: "/assets/stories/mobile/cityscapes.jpg",
  },
  {
    id: 3,
    date: "April 16th 2020",
    title: "18 Days Voyage",
    credit: "Alexei Borodin",
    desktop: "/assets/stories/desktop/18-days-voyage.jpg",
    mobile: "/assets/stories/mobile/18-days-voyage.jpg",
  },
  {
    id: 4,
    date: "April 16th 2020",
    title: "Architecturals",
    credit: "Samantha Brooke",
    desktop: "/assets/stories/desktop/architecturals.jpg",
    mobile: "/assets/stories/mobile/architecturals.jpg",
  },
  {
    id: 5,
    date: "April 16th 2020",
    title: "World Tour 2019",
    credit: "Timothy Wagner",
    desktop: "/assets/stories/desktop/world-tour.jpg",
    mobile: "/assets/stories/mobile/world-tour.jpg",
  },
  {
    id: 6,
    date: "April 16th 2020",
    title: "Unforeseen Corners",
    credit: "William Malcolm",
    desktop: "/assets/stories/desktop/unforeseen-corners.jpg",
    mobile: "/assets/stories/mobile/unforeseen-corners.jpg",
  },
  {
    id: 7,
    date: "April 16th 2020",
    title: "King on Africa: Part II",
    credit: "Tim Hillenburg",
    desktop: "/assets/stories/desktop/king-on-africa.jpg",
    mobile: "/assets/stories/mobile/king-on-africa.jpg",
  },
  {
    id: 8,
    date: "April 16th 2020",
    title: "The Trip to Nowhere",
    credit: "Felicia Rourke",
    desktop: "/assets/stories/desktop/trip-to-nowhere.jpg",
    mobile: "/assets/stories/mobile/trip-to-nowhere.jpg",
  },
  {
    id: 9,
    date: "April 16th 2020",
    title: "Rage of The Sea",
    credit: "Mohammed Abdul",
    desktop: "/assets/stories/desktop/rage-of-the-sea.jpg",
    mobile: "/assets/stories/mobile/rage-of-the-sea.jpg",
  },
  {
    id: 10,
    date: "April 16th 2020",
    title: "Running Free",
    credit: "Michelle",
    desktop: "/assets/stories/desktop/running-free.jpg",
    mobile: "/assets/stories/mobile/running-free.jpg",
  },
  {
    id: 11,
    date: "April 16th 2020",
    title: "Behind the Waves",
    credit: "Lamarr Wilson",
    desktop: "/assets/stories/desktop/behind-the-waves.jpg",
    mobile: "/assets/stories/mobile/behind-the-waves.jpg",
  },
  {
    id: 12,
    date: "April 16th 2020",
    title: "Calm Waters",
    credit: "Samantha Brooke",
    desktop: "/assets/stories/desktop/calm-waters.jpg",
    mobile: "/assets/stories/mobile/calm-waters.jpg",
  },
  {
    id: 13,
    date: "April 16th 2020",
    title: "The Milky Way",
    credit: "Benjamin Cruz",
    desktop: "/assets/stories/desktop/milky-way.jpg",
    mobile: "/assets/stories/mobile/milky-way.jpg",
  },
  {
    id: 14,
    date: "April 16th 2020",
    title: "Night at The Dark Forest",
    credit: "Mohammed Abdul",
    desktop: "/assets/stories/desktop/dark-forest.jpg",
    mobile: "/assets/stories/mobile/dark-forest.jpg",
  },
  {
    id: 15,
    date: "April 16th 2020",
    title: "Somwarpet’s Beauty",
    credit: "Michelle",
    desktop: "/assets/stories/desktop/somwarpet.jpg",
    mobile: "/assets/stories/mobile/somwarpet.jpg",
  },
  {
    id: 16,
    date: "April 16th 2020",
    title: "Land of Dreams",
    credit: "William Malcolm",
    desktop: "/assets/stories/desktop/land-of-dreams.jpg",
    mobile: "/assets/stories/mobile/land-of-dreams.jpg",
  },
];
